using System.Globalization;

namespace EAutopay.Upsells
{
    /// <summary>
    /// Encapsulates upsell in E-Autopay.
    /// </summary>
    public class Upsell
    {
        /// <summary>
        /// Gets upsell ID.
        /// </summary>
        public int ID { get; internal set; }

        /// <summary>
        /// Gets or sets ID of the product that upsell is based on.
        /// </summary>
        public int OriginID { get; set; }

        /// <summary>
        /// Gets ID of the product which the upsell belongs to.
        /// </summary>
        public int ParentID { get; internal set; }

        /// <summary>
        /// Gets upsell title generated by E-Atuopay.
        /// </summary>
        public string Title { get; internal set; }

        /// <summary>
        /// Gets or sets upsell price.
        /// </summary>
        public double Price { get; set; }

        /// <summary>
        /// Gets or sets URI for the "thank you" page.
        /// </summary>
        public string SuccessUri { get; set; }

        /// <summary>
        /// Gets URI for ordering upsell.
        /// </summary>
        public string ClientUri { get; internal set; }

        /// <summary>
        /// Returns True if upsell doesn't exist in E-Autopay. Otherwise - False.
        /// </summary>
        public bool IsNew
        {
            get { return ID == 0; }
            internal set { ID = 0; }
        }

        /// <summary>
        /// Gets culture-independent value of the price.
        /// </summary>
        public string PriceInvariant
        {
            get { return Price.ToString("F", CultureInfo.InvariantCulture);}
        }
    }
}
