using System.Globalization;

namespace EAutopay.Upsells
{
    /// <summary>
    /// Encapsulates upsell in E-Autopay.
    /// </summary>
    public class Upsell
    {
        /// <summary>
        /// Gets the upsell ID.
        /// </summary>
        public int ID { get; internal set; }

        /// <summary>
        /// Gets or sets the ID of the product that upsell is based on.
        /// </summary>
        public int OriginID { get; set; }

        /// <summary>
        /// Gets the ID of the product which the upsell belongs to.
        /// </summary>
        public int ParentID { get; internal set; }

        /// <summary>
        /// Gets the upsell title generated by E-Atuopay.
        /// </summary>
        public string Title { get; internal set; }

        /// <summary>
        /// Gets or sets the upsell price.
        /// </summary>
        public double Price { get; set; }

        /// <summary>
        /// Gets or sets the URI for the "thank you" page.
        /// </summary>
        public string SuccessUri { get; set; }

        /// <summary>
        /// Gets the URI for ordering upsell.
        /// </summary>
        public string ClientUri { get; internal set; }

        /// <summary>
        /// Determines whether the upsell exists in E-Autopay.
        /// </summary>
        public bool IsNew
        {
            get { return ID == 0; }
            internal set { ID = 0; }
        }

        /// <summary>
        /// Gets the culture-independent value of the price.
        /// </summary>
        public string PriceInvariant
        {
            get { return Price.ToString("F", CultureInfo.InvariantCulture);}
        }
    }
}
